[profile.default]
libs = ['lib']
fs_permissions = [ {access = "read-write", path = "./"} ]
optimizer = true
optimizer_runs = 999999
solc_version = "0.8.25"
[dotenv]
path = ".env"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config